const BOOK = window.JOSHUA_CONTENT;
const $ = s => document.querySelector(s);
const app = document.getElementById('app');
const STORAGE='journey-through-joshua-v1';
const REVIEW_INTERVALS=[1,3,7,14,30,90];
let route={page:'home',chapter:null,encounter:null};
let ui={answers:{},submitted:{},showEvidence:{}};

function baseState(){return {activeProfile:null,profiles:{}}}
function newProfile(name){return {name,created:Date.now(),completedEncounters:[],completedChapters:[],answers:{},insights:[],discoveries:[],journal:[],reviews:{},memory:[],days:{}}}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||baseState()}catch{return baseState()}}
let state=load();
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function profile(){return state.activeProfile?state.profiles[state.activeProfile]:null}
function ensureProfile(){if(!profile())return false;return true}
function markDay(){const p=profile(); if(!p)return; const d=new Date().toISOString().slice(0,10);p.days[d]=true;save()}
function mastery(ch){const p=profile();if(!p)return 0;const total=ch.encounters.length;const done=ch.encounters.filter(e=>p.completedEncounters.includes(e.id)).length;return Math.round(done/total*100)}
function allQuestions(){return BOOK.chapters.flatMap(c=>c.encounters.flatMap(e=>e.questions.map(q=>({...q,chapter:c.number,encounter:e.id,encounterTitle:e.title}))))}
function dueQuestions(){const p=profile();if(!p)return[];const now=Date.now();return allQuestions().filter(q=>p.answers[q.id] && (!p.reviews[q.id] || p.reviews[q.id].due<=now));}
function stats(){const p=profile(); if(!p)return {chapters:0,insights:0,reviews:0,journal:0};return {chapters:p.completedChapters.length,insights:p.insights.length,reviews:dueQuestions().length,journal:p.journal.length}}
function nav(){return `<nav class="nav">${[['home','⌂','Journey'],['bible','▤','Bible'],['review','↻','Review'],['journal','✎','Journal'],['profile','◎','Profile']].map(([p,i,l])=>`<button data-nav="${p}" class="${route.page===p?'active':''}"><b>${i}</b>${l}</button>`).join('')}</nav>`}
function top(){const p=profile();return `<div class="topbar"><div class="brand"><div class="brand-mark">J</div><div><strong>Journey Through Joshua</strong><small>NKJV Study Edition</small></div></div><button class="profile-pill" data-nav="profile">${p?p.name:'Choose profile'}</button></div>`}
function shell(content){app.innerHTML=`<div class="shell">${top()}<main>${content}</main>${nav()}</div>`;bindGlobal()}
function bindGlobal(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>go('chapter',+b.dataset.chapter));document.querySelectorAll('[data-study]').forEach(b=>{b.onclick=()=>{const [c,e]=b.dataset.study.split('|');go('study',+c,e)}});}
function go(page,chapter=null,encounter=null){route={page,chapter,encounter};ui={answers:{},submitted:{},showEvidence:{}};render();scrollTo(0,0)}
function requireProfile(){if(profile())return true;showProfileModal();return false}
function home(){const s=stats(),p=profile();const next=nextEncounter();return `<section class="hero"><div class="eyebrow">Your Scripture Journey</div><h1>Walk through Joshua. Remember what God has done.</h1><p>Study the text, investigate the details, collect insights, and revisit what you have learned over time.</p><button class="primary" id="continue">${next?'Continue Journey':'Begin Joshua'}</button></section><div class="grid"><div class="card stat"><strong>${s.chapters}/24</strong><small>Joshua chapters studied</small></div><div class="card stat"><strong>${s.insights}</strong><small>Insights discovered</small></div><div class="card stat"><strong>${s.reviews}</strong><small>Reviews ready</small></div><div class="card stat"><strong>${s.journal}</strong><small>Journal entries</small></div></div><div class="section-title"><h2>Joshua 1–4</h2><span>First journey arc</span></div><div class="chapter-list">${BOOK.chapters.map(ch=>chapterRow(ch)).join('')}</div>`}
function nextEncounter(){const p=profile();if(!p)return BOOK.chapters[0].encounters[0];for(const c of BOOK.chapters)for(const e of c.encounters)if(!p.completedEncounters.includes(e.id))return {...e,chapter:c.number};return null}
function chapterRow(ch){const m=mastery(ch);return `<div class="chapter ${m===100?'done':''}"><div class="chapter-num">${ch.number}</div><div class="chapter-body"><strong>${ch.title}</strong><small>${ch.theme} · ${ch.encounters.length} encounters</small><div class="progress"><i style="width:${m}%"></i></div></div><button class="ghost" data-chapter="${ch.number}">Open</button></div>`}
function bible(){const ot=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings'];return `<h1 class="page-title">Bible Library</h1><p class="muted">Study modules are added independently. Scripture itself is never locked behind game progress.</p><div class="section-title"><h2>Old Testament</h2><span>History module</span></div><div class="book-grid">${ot.map(b=>`<button class="book-tile ${b==='Joshua'?'available':''}" ${b==='Joshua'?'data-open-joshua':''}><strong>${b}</strong><small>${b==='Joshua'?'Available · 1–4 built':'Study module not yet available'}</small></button>`).join('')}</div><div class="section-title"><h2>Joshua Map</h2><span>Explore sequentially or jump to a chapter</span></div>${mapHtml()}`}
function mapHtml(){return `<div class="map">${BOOK.chapters.map((ch,i)=>{const m=mastery(ch),current=m<100 && BOOK.chapters.slice(0,i).every(x=>mastery(x)===100);return `<div class="map-node ${m===100?'done':''} ${current?'current':''}"><div class="node-dot">${['📜','🧵','🌊','🪨'][i]||ch.number}</div><div class="node-card"><span class="badge">Joshua ${ch.number}</span><h3>${ch.title}</h3><p class="muted">${ch.summary}</p><button class="ghost" data-chapter="${ch.number}">${m?'Continue':'Explore'}</button></div></div>`}).join('')}</div>`}
function chapterPage(n){const ch=BOOK.chapters.find(c=>c.number===n);if(!ch)return home();const p=profile();return `<button class="ghost" data-nav="bible">← Joshua map</button><h1 class="page-title">Joshua ${ch.number}: ${ch.title}</h1><p class="muted">${ch.summary}</p><div class="chips"><span class="chip">${ch.theme}</span><span class="chip">${ch.encounters.length} encounters</span><span class="chip">${mastery(ch)}% journey progress</span></div><div class="chapter-list">${ch.encounters.map((e,i)=>{const done=p?.completedEncounters.includes(e.id);return `<div class="chapter ${done?'done':''}"><div class="chapter-num">${done?'✓':i+1}</div><div class="chapter-body"><strong>${e.title}</strong><small>${e.passage} · ${e.type}</small></div><button class="secondary" data-study="${ch.number}|${e.id}">${done?'Revisit':'Begin'}</button></div>`}).join('')}</div><div class="card reflection" style="margin-top:18px"><h2>Chapter reflection</h2><p class="muted">Reflection is never graded.</p>${ch.reflection.map((r,i)=>`<label><strong>${r}</strong><textarea data-reflect="${n}-${i}" placeholder="Write your reflection…"></textarea></label>`).join('')}<button class="primary" id="save-reflection">Save reflection</button></div>`}
function studyPage(n,id){const ch=BOOK.chapters.find(c=>c.number===n);const e=ch?.encounters.find(x=>x.id===id);if(!e)return chapterPage(n);const done=profile()?.completedEncounters.includes(e.id);return `<button class="ghost" data-chapter="${n}">← Joshua ${n}</button><section class="study-head"><div class="eyebrow">${e.type} Encounter</div><h1>${e.title}</h1><p>${e.passage} · NKJV</p></section><div class="passage-box"><strong>Read ${e.passage} in the NKJV</strong><p>${e.intro}</p><div class="notice">The NKJV is copyrighted by Thomas Nelson. This prototype uses NKJV references and study material without reproducing the full translation. Licensed NKJV text can be connected later.</div></div>${e.questions.map(q=>questionHtml(q)).join('')}<div id="reward-area">${done?rewardHtml(e):''}</div><div class="controls"><button class="primary" id="complete-encounter">${done?'Revisit complete':'Complete encounter'}</button></div>`}
function optionKey(q,i){return `${q.id}:${i}`}
function isSelected(q,i){const a=ui.answers[q.id];return Array.isArray(a)?a.includes(i):a===i}
function questionHtml(q){const sub=ui.submitted[q.id];let body='';if(q.kind==='order'){const arr=ui.answers[q.id]||q.options.map((_,i)=>i);body=`<div id="order-${q.id}">${arr.map((idx,pos)=>`<button class="option" data-order="${q.id}|${pos}"><span>${pos+1}.</span>${q.options[idx]}</button>`).join('')}</div><div class="controls"><button class="ghost" data-reset-order="${q.id}">Reset order</button></div>`}else{body=q.options.map((o,i)=>`<button class="option ${isSelected(q,i)?'selected':''} ${sub?answerClass(q,i):''}" data-answer="${q.id}|${i}"><span>${q.kind==='multi'?'□':'○'}</span>${o}</button>`).join('')}
return `<div class="question" data-q="${q.id}"><span class="badge">${q.level}</span><h3>${q.prompt}</h3>${body}<div class="controls"><button class="secondary" data-submit="${q.id}">${sub?'Answered':'Check answer'}</button>${sub?`<button class="ghost" data-evidence="${q.id}">Show me in Scripture</button>`:''}</div>${sub?feedbackHtml(q):''}</div>`}
function answerClass(q,i){const ok=correct(q);if(q.kind==='multi')return q.answer.includes(i)?'correct':(isSelected(q,i)?'wrong':'');return i===q.answer?'correct':(isSelected(q,i)&&!ok?'wrong':'')}
function correct(q){const a=ui.answers[q.id];if(q.kind==='multi')return Array.isArray(a)&&a.slice().sort().join(',')===q.answer.slice().sort().join(',');if(q.kind==='order')return Array.isArray(a)&&a.join(',')===q.answer.join(',');return a===q.answer}
function feedbackHtml(q){return `<div class="feedback"><strong>${correct(q)?'Correct':'Look again'}</strong><div>${q.explanation}</div>${ui.showEvidence[q.id]?`<div class="evidence">Evidence: ${q.evidence} — open your NKJV Bible and verify it in the text.</div>`:''}</div>`}
function rewardHtml(e){return `<div class="insight"><div class="eyebrow">Insight discovered</div><h3>${e.insight.title}</h3><p>${e.insight.text}</p><strong>${e.insight.ref}</strong></div><div class="discovery"><div class="eyebrow">${e.discovery.type} discovery</div><h3>${e.discovery.name}</h3><p>${e.discovery.text}</p></div>${e.memory?`<div class="card"><strong>${e.memory.ref}</strong><p>${e.memory.prompt}</p><button class="ghost" id="add-memory">Add to memory list</button></div>`:''}`}
function review(){if(!requireProfile())return '';const due=dueQuestions();if(!due.length)return `<h1 class="page-title">Review</h1><div class="empty"><h3>Nothing is due right now.</h3><p>Your review queue grows as you study. Questions return over increasing intervals when you remember them correctly.</p></div>`;const q=due[0];return `<h1 class="page-title">Ready to Review</h1><p class="muted">${due.length} question${due.length===1?'':'s'} ready · Joshua ${q.chapter}</p><div class="review-card"><span class="badge">${q.level}</span><h2>${q.prompt}</h2>${q.options.map((o,i)=>`<button class="option" data-review-answer="${q.id}|${i}">${o}</button>`).join('')}<div id="review-feedback"></div></div>`}
function journal(){if(!requireProfile())return '';const p=profile();return `<h1 class="page-title">Journal</h1><p class="muted">Your reflections, discoveries, and insights stay with your local profile.</p><div class="section-title"><h2>My Notes</h2><span>${p.journal.length}</span></div>${p.journal.length?p.journal.slice().reverse().map(j=>`<div class="card"><strong>Joshua ${j.chapter}</strong><small class="muted"> · ${new Date(j.date).toLocaleDateString()}</small><p>${escapeHtml(j.prompt)}</p><p>${escapeHtml(j.text)}</p></div>`).join(''):'<div class="empty">No journal entries yet.</div>'}<div class="section-title"><h2>Insights</h2><span>${p.insights.length}</span></div><div class="collection-grid">${p.insights.map(x=>`<div class="collection-item"><span class="badge">${x.ref}</span><h3>${x.title}</h3><p>${x.text}</p></div>`).join('')||'<div class="empty">Study an encounter to discover your first insight.</div>'}</div><div class="section-title"><h2>Discoveries</h2><span>${p.discoveries.length}</span></div><div class="collection-grid">${p.discoveries.map(x=>`<div class="collection-item"><span class="badge">${x.type}</span><h3>${x.name}</h3><p>${x.text}</p></div>`).join('')}</div>`}
function profilePage(){const p=profile();return `<h1 class="page-title">Profiles</h1><p class="muted">Each local profile has independent progress, reviews, discoveries, and journal entries.</p>${Object.entries(state.profiles).map(([id,x])=>`<div class="profile-card ${id===state.activeProfile?'active':''}"><div class="row"><div><strong>${escapeHtml(x.name)}</strong><small class="muted" style="display:block">${x.completedChapters.length} chapter${x.completedChapters.length===1?'':'s'} studied</small></div><button class="ghost" data-switch="${id}">${id===state.activeProfile?'Active':'Switch'}</button></div></div>`).join('')||'<div class="empty">Create your first profile to begin.</div>'}<button class="primary" id="new-profile">+ New profile</button>${p?`<div class="section-title"><h2>${escapeHtml(p.name)}’s Journey</h2><span>Stored on this device</span></div><div class="grid"><div class="card stat"><strong>${p.completedChapters.length}</strong><small>Chapters studied</small></div><div class="card stat"><strong>${p.completedEncounters.length}</strong><small>Encounters completed</small></div><div class="card stat"><strong>${p.insights.length}</strong><small>Insights</small></div><div class="card stat"><strong>${Object.keys(p.days).length}</strong><small>Days in the Word</small></div></div>`:''}`}
function render(){let c='';if(route.page==='home')c=home();else if(route.page==='bible')c=bible();else if(route.page==='chapter')c=chapterPage(route.chapter);else if(route.page==='study')c=studyPage(route.chapter,route.encounter);else if(route.page==='review')c=review();else if(route.page==='journal')c=journal();else if(route.page==='profile')c=profilePage();shell(c);bindPage();if(!state.activeProfile && route.page!=='profile')setTimeout(showProfileModal,80)}
function bindPage(){
  if($('#continue'))$('#continue').onclick=()=>{if(!requireProfile())return;const e=nextEncounter();if(e)go('study',e.chapter||BOOK.chapters.find(c=>c.encounters.some(x=>x.id===e.id)).number,e.id);else go('bible')};
  if($('[data-open-joshua]'))$('[data-open-joshua]').onclick=()=>go('chapter',1);
  document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const [qid,si]=b.dataset.answer.split('|'),i=+si,q=allQuestions().find(x=>x.id===qid);if(ui.submitted[qid])return;if(q.kind==='multi'){const a=ui.answers[qid]||[];ui.answers[qid]=a.includes(i)?a.filter(x=>x!==i):[...a,i]}else ui.answers[qid]=i;renderStudyPreserve()});
  document.querySelectorAll('[data-submit]').forEach(b=>b.onclick=()=>{const q=allQuestions().find(x=>x.id===b.dataset.submit);if(ui.answers[q.id]===undefined)return alert('Choose an answer first.');ui.submitted[q.id]=true;const p=profile();if(p){p.answers[q.id]={correct:correct(q),date:Date.now()};scheduleReview(q.id,correct(q));save()}renderStudyPreserve()});
  document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{ui.showEvidence[b.dataset.evidence]=!ui.showEvidence[b.dataset.evidence];renderStudyPreserve()});
  document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const [qid,sp]=b.dataset.order.split('|'),pos=+sp;const q=allQuestions().find(x=>x.id===qid);let a=ui.answers[qid]||q.options.map((_,i)=>i);if(pos<a.length-1)[a[pos],a[pos+1]]=[a[pos+1],a[pos]];else [a[pos],a[0]]=[a[0],a[pos]];ui.answers[qid]=a;renderStudyPreserve()});
  document.querySelectorAll('[data-reset-order]').forEach(b=>b.onclick=()=>{const q=allQuestions().find(x=>x.id===b.dataset.resetOrder);ui.answers[q.id]=q.options.map((_,i)=>i);renderStudyPreserve()});
  if($('#complete-encounter'))$('#complete-encounter').onclick=completeEncounter;
  if($('#save-reflection'))$('#save-reflection').onclick=saveReflection;
  document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{state.activeProfile=b.dataset.switch;save();render()});
  if($('#new-profile'))$('#new-profile').onclick=showProfileModal;
  document.querySelectorAll('[data-review-answer]').forEach(b=>b.onclick=()=>answerReview(b));
  if($('#add-memory'))$('#add-memory').onclick=addMemory;
}
function renderStudyPreserve(){const y=scrollY;const c=studyPage(route.chapter,route.encounter);shell(c);bindPage();requestAnimationFrame(()=>scrollTo(0,y))}
function scheduleReview(qid,wasCorrect){const p=profile();const r=p.reviews[qid]||{step:0};r.step=wasCorrect?Math.min(r.step+1,REVIEW_INTERVALS.length-1):0;const days=REVIEW_INTERVALS[r.step];r.due=Date.now()+days*86400000;p.reviews[qid]=r}
function completeEncounter(){if(!requireProfile())return;const ch=BOOK.chapters.find(c=>c.number===route.chapter),e=ch.encounters.find(x=>x.id===route.encounter);const unanswered=e.questions.filter(q=>!ui.submitted[q.id] && !profile().answers[q.id]);if(unanswered.length)return alert('Complete the study questions before finishing this encounter.');const p=profile();if(!p.completedEncounters.includes(e.id))p.completedEncounters.push(e.id);if(!p.insights.some(x=>x.ref===e.insight.ref&&x.title===e.insight.title))p.insights.push(e.insight);if(!p.discoveries.some(x=>x.name===e.discovery.name))p.discoveries.push(e.discovery);if(ch.encounters.every(x=>p.completedEncounters.includes(x.id))&&!p.completedChapters.includes(ch.number))p.completedChapters.push(ch.number);markDay();save();renderStudyPreserve();$('#reward-area')?.scrollIntoView({behavior:'smooth',block:'center'})}
function saveReflection(){if(!requireProfile())return;const ch=BOOK.chapters.find(c=>c.number===route.chapter),p=profile();document.querySelectorAll('[data-reflect]').forEach((t,i)=>{const text=t.value.trim();if(text)p.journal.push({chapter:ch.number,prompt:ch.reflection[i],text,date:Date.now()})});markDay();save();alert('Reflection saved to your journal.');document.querySelectorAll('[data-reflect]').forEach(t=>t.value='')}
function answerReview(btn){const [qid,si]=btn.dataset.reviewAnswer.split('|'),i=+si,q=allQuestions().find(x=>x.id===qid),p=profile();const ok=(q.kind==='single'?i===q.answer:(q.kind==='multi'?q.answer.includes(i):false));scheduleReview(qid,ok);p.answers[qid]={correct:ok,date:Date.now()};markDay();save();document.querySelectorAll('[data-review-answer]').forEach(x=>x.disabled=true);$('#review-feedback').innerHTML=`<div class="feedback"><strong>${ok?'Remembered':'Review it again'}</strong><p>${q.explanation}</p><div class="evidence">Evidence: ${q.evidence}. Verify it in your NKJV Bible.</div><button class="primary" id="next-review">Next</button></div>`;$('#next-review').onclick=()=>render()}
function addMemory(){const ch=BOOK.chapters.find(c=>c.number===route.chapter),e=ch.encounters.find(x=>x.id===route.encounter),p=profile();if(e.memory&&!p.memory.some(x=>x.ref===e.memory.ref)){p.memory.push(e.memory);save()}alert('Added to your memory list.')}
function showProfileModal(){if(document.querySelector('.modal'))return;const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><div class="eyebrow">Local profile</div><h2>Who is studying today?</h2><p class="muted">Progress stays on this device in this prototype.</p><input id="profile-name" maxlength="30" placeholder="Name"/><div class="controls"><button class="primary" id="create-profile">Create profile</button>${state.activeProfile?'<button class="ghost" id="close-modal">Cancel</button>':''}</div></div>`;document.body.appendChild(m);$('#create-profile').onclick=()=>{const name=$('#profile-name').value.trim();if(!name)return;const id='p'+Date.now();state.profiles[id]=newProfile(name);state.activeProfile=id;save();m.remove();render()};if($('#close-modal'))$('#close-modal').onclick=()=>m.remove();$('#profile-name').focus()}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
